config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :posts, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  get 'homes/about', to: 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image  
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :shop_name, presence: true
  validates :shop_address, presence: true

  has_many :favorites, dependent: :destroy
 def favorited_by?(user)
   favorites.exists?(user_id: user.id)
 end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @post = Post.new
  end
  
  def index
    @post = Post.new
    @posts = Post.all
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "You have created post successfully."
      redirect_to post_path(@post)
    else
      @posts = Post.all
      @user = current_user
      render :index
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have updated post successfully."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @posts = @user.posts
    @post_new = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :shop_name, :shop_address,)
  end

  def correct_user
    @post = Post.find(params[:id])
    @user = @post.user
   unless @user == current_user
    redirect_to(posts_path) 
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @user = current_user
    @users = User.all
    @post = Post.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user) 
    else
      render :edit
    end 
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_btn.html.erb
<% if post.favorited_by?(current_user) %>
  <%= link_to post_favorites_path(post), method: :delete, class: "like-btn favorited" do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <span class="favorite-count"><%= post.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to post_favorites_path(post), method: :post, class: "like-btn not-favorited" do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <span class="favorite-count"><%= post.favorites.count %></span>
  <% end %>
<% end %>

app/views/homes/about.html.erb
    <%= stylesheet_link_tag 'about', media: 'all' %>
    <div class="container">
        <h2>ジムなびへようこそ！</h2>
        <p><strong>ジムなび</strong>は、24時間営業のジムを探すあなたのための究極のガイドです。<br/>
        私たちのサイトでは、全国各地の24時間ジムの詳細なレビューや評価、ユーザーの体験談を提供しています。<br/>
        忙しいライフスタイルの中でも、自分にぴったりのジムを見つけるお手伝いをします。</p>
        
        <h3>主な機能</h3>
        <ul>
            <li><strong>レビューと評価</strong>: ユーザーの実際の体験をもとにしたリアルなレビューと評価を閲覧できます。</li>
            <li><strong>ジム検索</strong>: 地域や目的に応じて最適なジムを簡単に検索できます。</li>
            <li><strong>詳細情報</strong>: 各ジムの設備、料金プラン、アクセス方法など、詳細な情報を提供しています。</li>
        </ul>
        
        <p><strong>なぜジムなび？</strong><br>
        私たちはユーザーが信頼できる情報を提供し、<br/>
        満足のいくフィットネス体験を得られるよう全力でサポートします。<br/>
        初心者から上級者まで、あらゆるフィットネスレベルに対応するジム情報を揃えており、<br/>
        フィットネスライフを充実させるためのパートナーとなります。</p>
        
        <p>今すぐ<strong>ジムなび</strong>であなたに最適な24時間ジムを見つけましょう!!</p>
    </div>

app/views/homes/top.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-11 col-sm-10 col-lg-8 col-xl-6 text-center">
      <h1 class="mb-4"><strong>ジムなび</strong> !</h1>
      <p class="mb-4">こちらからログイン、会員登録をしてください</p>
      
      <div class="btn-wrapper">
        <div class="row mb-3">
          <div class="col-12">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-info btn-block btn-lg" %>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <%= link_to "会員登録", new_user_registration_path, class: "btn btn-success btn-block btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid", style="background-color: #deb887; margin-bottom: 50px; padding: 20px;">
    <nav class="navbar navbar-expand-md navbar-light">
      <div style="position: absolute; top: 0; right: 0; display: flex;">
        <li class="nav-item">
         <%= link_to "About", about_path,class: 'btn btn-outline-secondary btn-sm mx-3' %>
        </li>
        <li class="nav-item">
         <%= link_to "商品一覧", post_path,class: 'btn btn-outline-secondary btn-sm mx-3' %>
        </li>
        <li class="nav-item">
         <%= link_to "新規登録", new_customer_registration_path,class: 'btn btn-outline-secondary btn-sm mx-3' %>
        </li>
         <li class="nav-item"><%= link_to "ログイン", new_customer_session_path,class: 'btn btn-outline-secondary btn-sm mx-3' %>
        </li>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>GymNavi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a0909bb4ab.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
    <header>
        <%= link_to root_path, class: "header-title navbar-brand" do %>
            <%= image_tag("icon.jpg", class: "logo") %>
        <% end %>
        <ul>
            <% if user_signed_in? %>
                <li>
                    <%= link_to '投稿フォーム', new_post_path, class: 'btn btn-secondary btn-sm mx-3' %>
                </li>
                <li>
                    <%= link_to '投稿一覧', posts_path, class: 'btn btn-secondary btn-sm mx-3' %>
                </li>
                <li>
                    <%= link_to 'マイページ', user_path(current_user.id), class: 'btn btn-secondary btn-sm mx-3' %>
                </li>
                <li>
                    <%= link_to 'ログアウト', destroy_user_session_path, class: 'btn btn-secondary btn-sm mx-3', method: :delete %>
                </li>
            <% else %>
                <li>
                    <%= link_to 'どんなサイト？', about_path, class: 'btn btn-secondary btn-sm mx-3' %>
                </li>
            <% end %>
        </ul>
    </header>
    <main>
        <% flash.each do |message_type, message| %>
            <div class="flash-message <%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
    </main>
    <footer>
        <div class='container'>
            <div class='row'>
                <div class='col text-center'>
                    <p class="footer-text">GymNavi.inc</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/views/posts/_posts.html.erb
<div class='col-md-3'>
		<% if post.errors.any? %>
			<%= post.errors.count %>errors prohibited this user from being saved:
			<ul>
				<% post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
	    <h2>ユーザー情報</h2>
	    <table class='table'>
	      <tr>
	        <%= image_tag user.get_profile_image(100,100) %>
	      </tr>
	      <tr>
	        <th>ユーザー名</th>
	        <th><%= user.name %></th>
	      </tr>
	    </table>
	    <div class='row'>
			  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
				ユーザー編集 
				  <i class="fas fa-user-cog"></i>
				<% end %>
	    </div>
	    <h2 class="mt-3">新規投稿</h2>
	    <%= form_with model: post do |f| %>
        <h4>タイトル</h4>
        <%= f.text_field :title %>
        <h4>内容</h4>
        <%= f.text_area :body %>
        <h4>ジムの名前</h4>
        <%= f.text_area :shop_name %>
        <h4>ジムの住所</h4>
        <%= f.text_area :shop_address %>
        <%= f.submit '投稿する' %>
      <% end %>
</div>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true, class: "p-4") do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@post.errors.count, "error") %>があります:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3 text-center">
    <%= form.label :タイトル %><br />
    <%= form.text_field :title, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :内容 %><br />
    <%= form.text_area :body, class: "form-control d-inline-block w-25", rows: 5 %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :ジムの名前 %><br />
    <%= form.text_field :shop_name, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :ジムの住所 %><br />
    <%= form.text_field :shop_address, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="text-center">
    <%= form.submit "更新", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <!-- Sidebar or user info section (if needed) -->
    <%= render 'posts/posts', {user: @user, post: @post} %>
    
    <div class="col-md-8 offset-md-1">
      <h2 class="mb-4">投稿一覧</h2>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>内容</th>
            <th>ジムの名前</th>
            <th>ジムの住所</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <!-- User Image -->
              <td>
                <%= link_to user_path(post.user.id) do %>
                  <%= image_tag post.user.get_profile_image(100, 100), class: "rounded-circle" %>
                <% end %>
              </td>

              <!-- Post Title -->
              <td>
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
              </td>

              <!-- Post Body -->
              <td><%= post.body %></td>

              <!-- Gym Name and Address -->
              <td><%= post.shop_name %></td>
              <td><%= post.shop_address %></td>

              <!-- Favorite Button -->
              <td>
                <%= render "favorites/btn", post: post %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true, class: "p-4") do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@post.errors.count, "error") %>があります:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3 text-center">
    <%= form.label :タイトル %><br />
    <%= form.text_field :title, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :内容 %><br />
    <%= form.text_area :body, class: "form-control d-inline-block w-25", rows: 5 %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :ジムの名前 %><br />
    <%= form.text_field :shop_name, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="form-group mb-3 text-center">
    <%= form.label :ジムの住所 %><br />
    <%= form.text_field :shop_address, class: "form-control d-inline-block w-25" %>
  </div>

  <div class="text-center">
    <%= form.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h2 class="mb-4">投稿詳細</h2>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>ユーザー</th>
            <th>投稿タイトル</th>
            <th>内容</th>
            <th>店舗名</th>
            <th>店舗住所</th>
            <% if @post.user == current_user %>
              <th>操作</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100, 100), class: "img-thumbnail" %>
                <div><%= @user.name %></div>
              <% end %>
            </td>
            <td>
              <%= link_to post_path(@post) do %>
                <%= @post.title %>
              <% end %>
            </td>
            <td><%= @post.body %></td>
            <td><%= @post.shop_name %></td>
            <td><%= @post.shop_address %></td>

            <% if @post.user == current_user %>
              <td class="d-flex">
                <%= link_to edit_post_path(@post), class: 'btn btn-primary mr-2' do %>
                  <button type="button" class="btn btn-primary">編集</button>
                <% end %>  
                <%= link_to post_path(@post), method: :delete, data: { confirm: '本当に削除しますか?' }, class: 'btn btn-danger' do %>
                  <button type="button" class="btn btn-danger">削除</button>
                <% end %>  
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this user from being saved:
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <h2>User info</h2>
    <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="inputName">名前</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
      <div class="form-group">
        <label for="inputImage">プロフィール画像</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> 
      </div>
      <div class="form-group">
      <%= f.submit "更新する" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'posts/posts' ,{user: @user, post: @post} %>
    
      <div class="col-md-8 offset-md-1">
      <h2>ユーザー一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>プロフィール画像</th>
            <th>ユーザー名</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show" ,user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <%= render 'posts/posts' ,{user: @user, post: @post} %>
	  <div class="col-md-8 offset-md-1">
      <h2 class="mb-4">投稿一覧</h2>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>内容</th>
            <th>ジムの名前</th>
            <th>ジムの住所</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <!-- User Image -->
              <td>
                <%= link_to user_path(post.user.id) do %>
                  <%= image_tag post.user.get_profile_image(100, 100), class: "rounded-circle" %>
                <% end %>
              </td>

              <!-- Post Title -->
              <td>
                <%= link_to post_path(post.id) do %>
                  <%= post.title %>
                <% end %>
              </td>

              <!-- Post Body -->
              <td><%= post.body %></td>

              <!-- Gym Name and Address -->
              <td><%= post.shop_name %></td>
              <td><%= post.shop_address %></td>

              <!-- Favorite Button -->
              <td>
                <%= render "favorites/btn", post: post %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
	</div>
</div>